SELECT Products.ProductName, Suppliers.CompanyName FROM Products INNER JOIN Suppliers ON Products.SupplierID = Suppliers.SupplierID
SELECT Customers.ContactName FROM Customers INNER JOIN Orders ON Customers.CustomerID = Orders.CustomerID WHERE Orders.OrderDate > '1998-03-01'
SELECT Customers.CustomerID, Customers.ContactName, Orders.OrderDate FROM Customers INNER JOIN Orders ON Customers.CustomerID = Orders.CustomerID
SELECT Products.ProductName, Products.UnitPrice, Suppliers.Address FROM Products INNER JOIN Suppliers ON Products.SupplierID = Suppliers.SupplierID WHERE Products.UnitPrice BETWEEN 20 AND 30
SELECT Products.ProductName, Products.UnitsInStock, Suppliers.CompanyName FROM Products INNER JOIN Suppliers ON Products.SupplierID = Suppliers.SupplierID WHERE Suppliers.CompanyName = 'Tokyo Traders'
SELECT DISTINCT Suppliers.ContactName, Suppliers.Phone FROM Suppliers INNER JOIN Products ON Suppliers.SupplierID = Products.SupplierID INNER JOIN [Order Details] ON Products.ProductID = [Order Details].ProductID INNER JOIN Orders ON [Order Details].OrderID = Orders.OrderID WHERE [Order Details].Quantity > Products.UnitsInStock
SELECT Products.ProductName FROM Products INNER JOIN [Order Details] ON Products.ProductID = [Order Details].ProductID INNER JOIN Orders ON [Order Details].OrderID = Orders.OrderID WHERE Orders.OrderDate = '1996-07-08'
SELECT Products.ProductName, Products.UnitPrice, Suppliers.Address FROM Products INNER JOIN Suppliers ON Products.SupplierID = Suppliers.SupplierID WHERE Products.UnitPrice BETWEEN 20 AND 30 AND Products.CategoryID IN (SELECT CategoryID FROM Categories WHERE CategoryName = 'Meat/Poultry')
SELECT Products.ProductName, Products.UnitPrice, Suppliers.CompanyName FROM Products INNER JOIN Suppliers ON Products.SupplierID = Suppliers.SupplierID WHERE Products.CategoryID IN (SELECT CategoryID FROM Categories WHERE CategoryName = 'Confections')
SELECT Customers.ContactName, Customers.Phone FROM Customers INNER JOIN Orders ON Customers.CustomerID = Orders.CustomerID INNER JOIN Shippers ON Orders.ShipVia = Shippers.ShipperID WHERE Shippers.CompanyName = 'United Package' AND YEAR(Orders.ShippedDate) = 1997
SELECT Customers.ContactName, Customers.Phone FROM Customers INNER JOIN Orders ON Customers.CustomerID = Orders.CustomerID INNER JOIN [Order Details] ON Orders.OrderID = [Order Details].OrderID INNER JOIN Products ON [Order Details].ProductID = Products.ProductID INNER JOIN Categories ON Products.CategoryID = Categories.CategoryID WHERE Categories.CategoryName = 'Confections'
SELECT DISTINCT e1.FirstName, e1.LastName, e2.FirstName, e2.LastName, e1.Title FROM Employees e1, Employees e2 WHERE e1.Title = e2.Title AND e1.EmployeeID <> e2.EmployeeID ORDER BY e1.Title;
WITH EmployeeHierarchy(EmployeeID, FirstName, LastName, ManagerID, Title) AS (SELECT EmployeeID, FirstName, LastName, ReportsTo, Title FROM Employees WHERE ReportsTo IS NULL UNION ALL SELECT e.EmployeeID, e.FirstName, e.LastName, e.ReportsTo, e.Title FROM Employees e INNER JOIN EmployeeHierarchy eh ON e.ReportsTo = eh.EmployeeID) SELECT * FROM EmployeeHierarchy
SELECT FirstName, LastName FROM Employees WHERE EmployeeID NOT IN (SELECT ReportsTo FROM Employees WHERE ReportsTo IS NOT NULL)